// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLTV.Models;

#nullable disable

namespace QLTV.Migrations
{
    [DbContext(typeof(QLTVContext))]
    [Migration("20241109143319_XoaCotTrangThaiDM")]
    partial class XoaCotTrangThaiDM
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QLTV.Models.TblDanhMuc", b =>
                {
                    b.Property<string>("SMaDanhMuc")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sMaDanhMuc");

                    b.Property<string>("STenDanhMuc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sTenDanhMuc");

                    b.HasKey("SMaDanhMuc")
                        .HasName("PK__tblDanhM__7D62A86F8FCB4038");

                    b.ToTable("tblDanhMuc", (string)null);
                });

            modelBuilder.Entity("QLTV.Models.TblDanhSachMuon", b =>
                {
                    b.Property<string>("SMaDanhSach")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sMaDanhSach");

                    b.Property<string>("SMaSach")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sMaSach");

                    b.Property<string>("SMaTheMuon")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sMaTheMuon");

                    b.HasKey("SMaDanhSach")
                        .HasName("PK__tblDanhS__8DBFA015847F2667");

                    b.HasIndex("SMaTheMuon");

                    b.ToTable("tblDanhSachMuon", (string)null);
                });

            modelBuilder.Entity("QLTV.Models.TblNguoiDung", b =>
                {
                    b.Property<string>("SMaNguoiDung")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sMaNguoiDung");

                    b.Property<DateTime?>("DNgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("dNgaySinh");

                    b.Property<string>("SCccd")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sCCCD");

                    b.Property<string>("SDiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sDiaChi");

                    b.Property<string>("SMaTheMuon")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sMaTheMuon");

                    b.Property<string>("STenNguoiDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sTenNguoiDung");

                    b.HasKey("SMaNguoiDung")
                        .HasName("PK__tblNguoi__47E09BE3C780583C");

                    b.HasIndex("SMaTheMuon");

                    b.ToTable("tblNguoiDung", (string)null);
                });

            modelBuilder.Entity("QLTV.Models.TblQuyen", b =>
                {
                    b.Property<string>("SId")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sID");

                    b.Property<int?>("IMaQuyen")
                        .HasColumnType("int")
                        .HasColumnName("iMaQuyen");

                    b.Property<string>("STenQuyen")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sTenQuyen");

                    b.HasKey("SId")
                        .HasName("PK__tblQuyen__DDDED94E1B414431");

                    b.ToTable("tblQuyen", (string)null);
                });

            modelBuilder.Entity("QLTV.Models.TblSach", b =>
                {
                    b.Property<string>("SMaSach")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sMaSach");

                    b.Property<double?>("FGiaTien")
                        .HasColumnType("float")
                        .HasColumnName("fGiaTien");

                    b.Property<int?>("ISoLuong")
                        .HasColumnType("int")
                        .HasColumnName("iSoLuong");

                    b.Property<string>("SDuongDan")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sDuongDan");

                    b.Property<string>("SMaDanhMuc")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sMaDanhMuc");

                    b.Property<string>("SMoTa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sMoTa");

                    b.Property<string>("SNhaXuatBan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sNhaXuatBan");

                    b.Property<string>("STenSach")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sTenSach");

                    b.Property<string>("STenTacGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sTenTacGia");

                    b.Property<string>("STrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("sTrangThai");

                    b.HasKey("SMaSach")
                        .HasName("PK__tblSach__BE472D1CE2D534AF");

                    b.HasIndex("SMaDanhMuc");

                    b.ToTable("tblSach", (string)null);
                });

            modelBuilder.Entity("QLTV.Models.TblTaiKhoan", b =>
                {
                    b.Property<string>("STaiKhoan")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sTaiKhoan");

                    b.Property<string>("SMaNguoiDung")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sMaNguoiDung");

                    b.Property<string>("SMaQuyen")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sMaQuyen");

                    b.Property<string>("SMatKhau")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sMatKhau");

                    b.HasKey("STaiKhoan")
                        .HasName("PK__tblTaiKh__868A5E9D88AE4BA6");

                    b.HasIndex("SMaNguoiDung");

                    b.HasIndex("SMaQuyen");

                    b.ToTable("tblTaiKhoan", (string)null);
                });

            modelBuilder.Entity("QLTV.Models.TblTheMuon", b =>
                {
                    b.Property<string>("SMaTheMuon")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sMaTheMuon");

                    b.Property<DateTime?>("DNgayMuon")
                        .HasColumnType("date")
                        .HasColumnName("dNgayMuon");

                    b.Property<DateTime?>("DNgayTra")
                        .HasColumnType("date")
                        .HasColumnName("dNgayTra");

                    b.Property<DateTime?>("DNgayTraDuKien")
                        .HasColumnType("date")
                        .HasColumnName("dNgayTraDuKien");

                    b.Property<DateTime?>("DNgayTraThucTe")
                        .HasColumnType("date")
                        .HasColumnName("dNgayTraThucTe");

                    b.Property<string>("STrangThai")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("sTrangThai");

                    b.HasKey("SMaTheMuon")
                        .HasName("PK__tblTheMu__21924A48D814BB79");

                    b.ToTable("tblTheMuon", (string)null);
                });

            modelBuilder.Entity("QLTV.Models.TblDanhSachMuon", b =>
                {
                    b.HasOne("QLTV.Models.TblSach", "SMaDanhSachNavigation")
                        .WithOne("TblDanhSachMuon")
                        .HasForeignKey("QLTV.Models.TblDanhSachMuon", "SMaDanhSach")
                        .IsRequired()
                        .HasConstraintName("FK__tblDanhSa__sMaDa__5629CD9C");

                    b.HasOne("QLTV.Models.TblTheMuon", "SMaTheMuonNavigation")
                        .WithMany("TblDanhSachMuons")
                        .HasForeignKey("SMaTheMuon")
                        .HasConstraintName("FK__tblDanhSa__sMaTh__5535A963");

                    b.Navigation("SMaDanhSachNavigation");

                    b.Navigation("SMaTheMuonNavigation");
                });

            modelBuilder.Entity("QLTV.Models.TblNguoiDung", b =>
                {
                    b.HasOne("QLTV.Models.TblTheMuon", "SMaTheMuonNavigation")
                        .WithMany("TblNguoiDungs")
                        .HasForeignKey("SMaTheMuon")
                        .HasConstraintName("FK__tblNguoiD__sMaTh__571DF1D5");

                    b.Navigation("SMaTheMuonNavigation");
                });

            modelBuilder.Entity("QLTV.Models.TblSach", b =>
                {
                    b.HasOne("QLTV.Models.TblDanhMuc", "SMaDanhMucNavigation")
                        .WithMany("TblSaches")
                        .HasForeignKey("SMaDanhMuc")
                        .HasConstraintName("FK__tblSach__sMaDanh__59FA5E80");

                    b.Navigation("SMaDanhMucNavigation");
                });

            modelBuilder.Entity("QLTV.Models.TblTaiKhoan", b =>
                {
                    b.HasOne("QLTV.Models.TblNguoiDung", "SMaNguoiDungNavigation")
                        .WithMany("TblTaiKhoans")
                        .HasForeignKey("SMaNguoiDung")
                        .HasConstraintName("FK__tblTaiKho__sMaNg__59063A47");

                    b.HasOne("QLTV.Models.TblQuyen", "SMaQuyenNavigation")
                        .WithMany("TblTaiKhoans")
                        .HasForeignKey("SMaQuyen")
                        .HasConstraintName("FK__tblTaiKho__sMaQu__5812160E");

                    b.Navigation("SMaNguoiDungNavigation");

                    b.Navigation("SMaQuyenNavigation");
                });

            modelBuilder.Entity("QLTV.Models.TblDanhMuc", b =>
                {
                    b.Navigation("TblSaches");
                });

            modelBuilder.Entity("QLTV.Models.TblNguoiDung", b =>
                {
                    b.Navigation("TblTaiKhoans");
                });

            modelBuilder.Entity("QLTV.Models.TblQuyen", b =>
                {
                    b.Navigation("TblTaiKhoans");
                });

            modelBuilder.Entity("QLTV.Models.TblSach", b =>
                {
                    b.Navigation("TblDanhSachMuon");
                });

            modelBuilder.Entity("QLTV.Models.TblTheMuon", b =>
                {
                    b.Navigation("TblDanhSachMuons");

                    b.Navigation("TblNguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
